### ISSUE TITLE
버그: 안들어가져요 들어가게 해줭 ㅜㅜ

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-13#168]
<img width="1644" alt="스크린샷 2019-12-06 14 13 15" src="https://user-images.githubusercontent.com/26241585/70297749-97a7a800-1832-11ea-8679-87f946b0263e.png">

**Comment by munsulim** [comment]
아직 입장불가라 ;;

**Comment by NBJ1995** [comment]
30분부터 입장 가능입니다. 오픈시간 지켜주세요 ㅜ 😢
