### ISSUE TITLE
반복하기 안에 회전하기를 반대방향으로 각각 주면 돌아가지 않습니다.

### ISSUE THREAD

**Issue by riverandeye** [connect-foundation/2019-13#230]
![image](https://user-images.githubusercontent.com/41494099/70775963-2da57a80-1dbf-11ea-8d03-4efedccb986d.png)

각각 독립적으로 돌아가는게 아니라, 둘의 합이 계산되서 돌아가는 것으로 보입니다.

**Comment by munsulim** [comment]
블록코딩 구조상 같은 프레임에 돌아가는 블록은 합산되어 돌아가도록 설계되어있습니다!
