### ISSUE TITLE
X Y 좌표를 바꾸는 기능에 음수가 들어가지 않습니다.

### ISSUE THREAD

**Issue by riverandeye** [connect-foundation/2019-13#231]
![image](https://user-images.githubusercontent.com/41494099/70776134-8e34b780-1dbf-11ea-85e8-e63a989b9cf7.png)

음수가 안들어감요.. 부덕이가 돌아오지 않아요 ㅠㅠ

근데 정말 사용성 좋게 잘 만드신거같아요 너무 재밌네요

**Comment by NBJ1995** [comment]
현재 음수가 숫자가 있을때 가장 앞에 넣을때만 들어갑니다 ㅜ 
0일때 -0이 안되서 사라지는데 다른숫자가 있으면 -가 잘 붙긴합니다
다른 버그 다 수정하고 이것도 좀 더 사용성 좋게 바꾸도록 하겠습니다

재밌게 즐겨주셔서 감사합니다 👍
